#Feature Engineering

In [1]:
import pandas as pd

df = pd.read_csv("../data/processed/cleaned_amazon_sales_dataset.csv")

In [3]:
import os

print(os.getcwd())

c:\Users\sarva\Desktop\data_analytics\RetailPulse\notebooks

In [4]:
import os

print(os.listdir("../data/raw"))

['amazon_sales_dataset.csv']

In [2]:
df['order_date'] = pd.to_datetime(df['order_date'])
df['ship_date'] = pd.to_datetime(df['ship_date'])
df['delivery_date'] = pd.to_datetime(df['delivery_date'])

In [3]:
df['order_month'] = df['order_date'].dt.month

In [4]:
df[['order_date', 'order_month']].head()

  order_date  order_month
0 2026-01-20            1
1 2026-01-04            1
2 2026-01-24            1
3 2026-01-17            1
4 2026-01-02            1

In [5]:
df['order_year'] = df['order_date'].dt.year

In [6]:
df[['order_date', 'order_year']].head()

  order_date  order_year
0 2026-01-20        2026
1 2026-01-04        2026
2 2026-01-24        2026
3 2026-01-17        2026
4 2026-01-02        2026

In [7]:
df['order_day'] = df['order_date'].dt.day

In [8]:
df[['order_date', 'order_day']].head()

  order_date  order_day
0 2026-01-20         20
1 2026-01-04          4
2 2026-01-24         24
3 2026-01-17         17
4 2026-01-02          2

In [9]:
df['order_day_of_week'] = df['order_date'].dt.day_name()

In [10]:
df[['order_date', 'order_day_of_week']].head()

  order_date order_day_of_week
0 2026-01-20           Tuesday
1 2026-01-04            Sunday
2 2026-01-24          Saturday
3 2026-01-17          Saturday
4 2026-01-02            Friday

In [11]:
df['delivery_time_days'] = (
    df['delivery_date'] - df['order_date']
).dt.days

In [12]:
df[['order_date', 'delivery_date', 'delivery_time_days']].head()

  order_date delivery_date  delivery_time_days
0 2026-01-20    2026-02-03                  14
1 2026-01-04    2026-01-21                  17
2 2026-01-24    2026-02-10                  17
3 2026-01-17    2026-02-06                  20
4 2026-01-02    2026-01-10                   8

In [13]:
df['shipping_time_days'] = (
    df['ship_date'] - df['order_date']
).dt.days

In [14]:
df[['order_date', 'ship_date', 'shipping_time_days']].head()

  order_date  ship_date  shipping_time_days
0 2026-01-20 2026-02-03                  14
1 2026-01-04 2026-01-10                   6
2 2026-01-24 2026-01-26                   2
3 2026-01-17 2026-01-17                   0
4 2026-01-02 2026-01-06                   4

In [15]:
df[df['ship_date'] < df['order_date']]

Empty DataFrame
Columns: [order_id, order_date, ship_date, delivery_date, order_status, customer_id, customer_name, country, state, city, product_id, product_name, category, sub_category, brand, quantity, unit_price, discount, shipping_cost, total_sales, payment_method, order_month, order_year, order_day, order_day_of_week, delivery_time_days, shipping_time_days]
Index: []

[0 rows x 27 columns]

In [16]:
df['delivery_delay'] = df['delivery_time_days'] - df['shipping_time_days']

In [17]:
df[['shipping_time_days', 'delivery_time_days', 'delivery_delay']].head()

   shipping_time_days  delivery_time_days  delivery_delay
0                  14                  14               0
1                   6                  17              11
2                   2                  17              15
3                   0                  20              20
4                   4                   8               4

In [18]:
df[df['delivery_date'] < df['order_date']]

Empty DataFrame
Columns: [order_id, order_date, ship_date, delivery_date, order_status, customer_id, customer_name, country, state, city, product_id, product_name, category, sub_category, brand, quantity, unit_price, discount, shipping_cost, total_sales, payment_method, order_month, order_year, order_day, order_day_of_week, delivery_time_days, shipping_time_days, delivery_delay]
Index: []

[0 rows x 28 columns]

In [19]:
df[['order_date', 'delivery_date']].head(10)

  order_date delivery_date
0 2026-01-20    2026-02-03
1 2026-01-04    2026-01-21
2 2026-01-24    2026-02-10
3 2026-01-17    2026-02-06
4 2026-01-02    2026-01-10
5 2026-01-05    2026-01-24
6 2026-01-16    2026-02-10
7 2026-01-06    2026-02-04
8 2026-01-07    2026-02-10
9 2026-01-14    2026-02-04

In [20]:
df.head()

,order_id,order_date,ship_date,delivery_date,order_status,customer_id,customer_name,country,state,city,...,shipping_cost,total_sales,payment_method,order_month,order_year,order_day,order_day_of_week,delivery_time_days,shipping_time_days,delivery_delay
0,A10001,2026-01-20,2026-02-03,2026-02-03,Delivered,C9811,Chris Davenport,India,Tennessee,Madisonmouth,...,112.96,55043.8752,COD,1,2026,20,Tuesday,14,14,0
1,A10006,2026-01-04,2026-01-10,2026-01-21,Delivered,C9866,Heather Campos,India,Colorado,Turnerville,...,29.90,156361.6760,COD,1,2026,4,Sunday,17,6,11
2,A10009,2026-01-24,2026-01-26,2026-02-10,Delivered,C9948,Chelsea Brown,India,South Carolina,Kendraton,...,144.57,74836.3124,UPI,1,2026,24,Saturday,17,2,15
3,A10011,2026-01-17,2026-01-17,2026-02-06,Delivered,C6925,Antonio Allen,India,Georgia,Lawrenceland,...,57.50,15576.0800,UPI,1,2026,17,Saturday,20,0,20
4,A10013,2026-01-02,2026-01-06,2026-01-10,Delivered,C9232,Veronica Villa,India,California,South Heather,...,120.87,3950.2968,COD,1,2026,2,Friday,8,4,4

In [21]:
df[['order_date', 'ship_date', 'delivery_date']].dtypes

order_date       datetime64[us]
ship_date        datetime64[us]
delivery_date    datetime64[us]
dtype: object

In [22]:
df['order_date'] = pd.to_datetime(df['order_date'])
df['ship_date'] = pd.to_datetime(df['ship_date'])
df['delivery_date'] = pd.to_datetime(df['delivery_date'])

In [23]:
df[['order_date', 'ship_date', 'delivery_date']].dtypes

order_date       datetime64[us]
ship_date        datetime64[us]
delivery_date    datetime64[us]
dtype: object

In [24]:
df['order_month'] = df['order_date'].dt.month

df[['order_date', 'order_month']].head()

  order_date  order_month
0 2026-01-20            1
1 2026-01-04            1
2 2026-01-24            1
3 2026-01-17            1
4 2026-01-02            1

In [25]:
df['order_year'] = df['order_date'].dt.year

df[['order_date', 'order_year']].head()

  order_date  order_year
0 2026-01-20        2026
1 2026-01-04        2026
2 2026-01-24        2026
3 2026-01-17        2026
4 2026-01-02        2026

In [26]:
df['order_day'] = df['order_date'].dt.day

df[['order_date', 'order_day']].head()

  order_date  order_day
0 2026-01-20         20
1 2026-01-04          4
2 2026-01-24         24
3 2026-01-17         17
4 2026-01-02          2

In [27]:
df['day_of_week'] = df['order_date'].dt.day_name()

df[['order_date', 'day_of_week']].head()

  order_date day_of_week
0 2026-01-20     Tuesday
1 2026-01-04      Sunday
2 2026-01-24    Saturday
3 2026-01-17    Saturday
4 2026-01-02      Friday

In [28]:
df['delivery_time'] = (df['delivery_date'] - df['order_date']).dt.days

df[['order_date', 'delivery_date', 'delivery_time']].head()

  order_date delivery_date  delivery_time
0 2026-01-20    2026-02-03             14
1 2026-01-04    2026-01-21             17
2 2026-01-24    2026-02-10             17
3 2026-01-17    2026-02-06             20
4 2026-01-02    2026-01-10              8

In [29]:
df['shipping_time'] = (df['ship_date'] - df['order_date']).dt.days

df[['order_date', 'ship_date', 'shipping_time']].head()

  order_date  ship_date  shipping_time
0 2026-01-20 2026-02-03             14
1 2026-01-04 2026-01-10              6
2 2026-01-24 2026-01-26              2
3 2026-01-17 2026-01-17              0
4 2026-01-02 2026-01-06              4

In [30]:
df['delivery_delay'] = (df['delivery_date'] - df['ship_date']).dt.days

df[['ship_date', 'delivery_date', 'delivery_delay']].head()

   ship_date delivery_date  delivery_delay
0 2026-02-03    2026-02-03               0
1 2026-01-10    2026-01-21              11
2 2026-01-26    2026-02-10              15
3 2026-01-17    2026-02-06              20
4 2026-01-06    2026-01-10               4

In [31]:
df.columns.tolist()

['order_id',
 'order_date',
 'ship_date',
 'delivery_date',
 'order_status',
 'customer_id',
 'customer_name',
 'country',
 'state',
 'city',
 'product_id',
 'product_name',
 'category',
 'sub_category',
 'brand',
 'quantity',
 'unit_price',
 'discount',
 'shipping_cost',
 'total_sales',
 'payment_method',
 'order_month',
 'order_year',
 'order_day',
 'order_day_of_week',
 'delivery_time_days',
 'shipping_time_days',
 'delivery_delay',
 'day_of_week',
 'delivery_time',
 'shipping_time']

In [32]:
for col in df.columns:
    print(col)

order_id
order_date
ship_date
delivery_date
order_status
customer_id
customer_name
country
state
city
product_id
product_name
category
sub_category
brand
quantity
unit_price
discount
shipping_cost
total_sales
payment_method
order_month
order_year
order_day
order_day_of_week
delivery_time_days
shipping_time_days
delivery_delay
day_of_week
delivery_time
shipping_time